short_name = "green-godot"
name = "Green Godot"
major = 3
minor = 6
patch = 0
status = "stable"
module_config = "green"
year = 2025
website = "https://github.com/Wolf-Pack-Clan/green-godot"
docs = "3.6"
