name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-mark hold firefox imagemagick \
        sudo apt update && sudo apt upgrade -y
        sudo apt install build-essential scons pkg-config \
          libx11-dev libxcursor-dev libxinerama-dev \
          libgl1-mesa-dev libglu-dev libasound2-dev \
          libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

    - name: Build
      env:
        SCONS_CACHE: ${{ github.workspace }}/.scons_cache
      run: |
        scons tools=no platform=android arch=armv7 lto=full \
          progress=yes debug_symbols=no module_gdnative_enabled=no \
          module_mobile_vr_enabled=no module_visual_script_enabled=no
  
    - name: Build with Gradle
      run: |
        cd platform/android/java
        ./gradlew generateGodotTemplates
        cd ../../../
        zip -r -9 bin.zip bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin.zip
