name: Android CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-mark hold firefox imagemagick \
        sudo apt update && sudo apt upgrade -y
        sudo apt install build-essential scons pkg-config \
          libx11-dev libxcursor-dev libxinerama-dev \
          libgl1-mesa-dev libglu-dev libasound2-dev \
          libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

    #- name: Restore cache
    #  uses: actions/cache@v4
    #  with:
    #    path: |
    #      /usr/local/lib/android/sdk
    #    key: ${{ runner.os }}-android-cache
    #    restore-keys: |
    #      ${{ runner.os }}-android-cache
    - name: setup ndk
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23c
        add-to-path: true
        local-cache: true

    - name: Build
      run: |
        scons tools=no platform=android arch=armv7 lto=full \
          progress=yes debug_symbols=no module_gdnative_enabled=no \
          module_mobile_vr_enabled=no module_visual_script_enabled=no
        scons tools=no platform=android arch=arm64v8 lto=full \
          progress=yes debug_symbols=no module_gdnative_enabled=no \
          module_mobile_vr_enabled=no module_visual_script_enabled=no
        scons tools=no platform=android arch=x86 lto=full \
          progress=yes debug_symbols=no module_gdnative_enabled=no \
          module_mobile_vr_enabled=no module_visual_script_enabled=no
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
  
    - name: Build with Gradle
      run: |
        cd platform/android/java
        chmod +x gradlew
        ./gradlew generateGodotTemplates
        cd ../../../
        zip -r -9 bin.zip bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin.zip
