name: Build

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      #- name: Cache APT packages
      #  uses: actions/cache@v4
      #  with:
      #    path: /var/cache/apt/archives
      #    key: ${{ runner.os }}-apt-${{ hashFiles('Dockerfile') }}

      #- name: Restore cache
      #  uses: actions/cache@v4
      #  with:
      #    path: |
      #      .scons_cache/
      #      .sconsign.dblite
      #    key: ${{ runner.os }}-cache #-${{ hashFiles('SConstruct', '**/*.cpp', '**/*.h', 'Dockerfile') }}
      #    restore-keys: |
      #      ${{ runner.os }}-cache

      - name: Install system dependencies
        run: |
          sudo apt-mark hold firefox imagemagick \
          sudo apt update && sudo apt upgrade -y
          sudo apt install build-essential scons pkg-config \
            libx11-dev libxcursor-dev libxinerama-dev \
            libgl1-mesa-dev libglu-dev libasound2-dev \
            libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Build
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache
        run: |
          scons tools=yes platform=x11 bits=64 arch=x64 lto=full \
            progress=yes debug_symbols=no module_gdnative_enabled=no \
            module_mobile_vr_enabled=no module_visual_script_enabled=no
          strip bin/godot.x11.tools.x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot.x11.tools.x64
          path: bin/godot.x11.tools.x64

      - name: List build output
        run: ls -l bin
