name: ☁ Server Builds [Production]
on: [workflow_call, workflow_dispatch]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.6
  #SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no module_mono_enabled=yes mono_static=yes mono_glue=no
  SCONSFLAGS: optimize=speed use_static_cpp=yes lto=full debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-server
  cancel-in-progress: true

jobs:
  build-server:
    # Stay one LTS before latest to increase portability of Linux artifacts.
    runs-on: "ubuntu-22.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- name: Linux Headless w/ Mono (target=release_debug, tools=yes)
          - name: Linux Headless (target=release_debug, tools=yes)
            #cache-name: server-editor-mono
            cache-name: server-editor
            sconsflags: module_mono_enabled=no mono_static=no mono_glue=no
            target: release_debug
            tools: true
            artifact: true

          #- name: Linux Server w/ Mono (target=release, tools=no)
          - name: Linux Server (target=release, tools=no)
            #cache-name: server-template-mono
            cache-name: server-template
            sconsflags: module_mono_enabled=no mono_static=no mono_glue=no
            target: release
            tools: false
            artifact: true

          - name: Linux Server (target=release_debug, tools=no)
            cache-name: server-template-debug
            sconsflags: module_mono_enabled=no mono_static=no mono_glue=no
            target: release_debug
            tools: false
            artifact: true

    steps:
      - uses: actions/checkout@v4

      - name: Linux dependencies
        shell: bash
        run: |
          # Azure repositories are flaky, remove them.
          sudo rm -f /etc/apt/sources.list.d/{azure,microsoft}*
          sudo apt-get update
          # The actual dependencies.
          sudo apt-get install --no-install-recommends build-essential pkg-config libx11-dev \
              libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
              libpulse-dev libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
              libspeechd-dev speech-dispatcher

      #- name: Restore Godot build cache
      #  uses: ./.github/actions/godot-cache-restore
      #  with:
      #    cache-name: ${{ matrix.cache-name }}
      #  continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: server
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      #- name: Save Godot build cache
      #  uses: ./.github/actions/godot-cache-save
      #  with:
      #    cache-name: ${{ matrix.cache-name }}
      #  continue-on-error: true

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          strip bin/godot_server.*
          chmod +x bin/godot_server.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
